//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Reader_zh-cn.rc
//
#define IDC_SAVE                        3
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    104
#define IDS_ERROR                       104
#define IDM_ABOUT                       105
#define IDS_WARN                        105
#define IDM_EXIT                        106
#define IDS_SUCC                        106
#define IDC_STATUSBAR                   107
#define IDI_READER                      108
#define IDS_INVALID_LINEGAP             108
#define IDI_SMALL                       109
#define IDS_INVALID_INBORDER            109
#define IDC_READER                      110
#define IDS_INVALID_AUTOPAGE            111
#define IDS_INVALID_PORT                112
#define IDS_PLS_SEL_IMG                 113
#define IDS_INVALID_IMG                 114
#define IDS_IMG_NOT_EXIST               115
#define IDS_INVALID_LAYOUT              116
#define IDS_INVALID_VALUE               117
#define IDS_BOOKMARK                    118
#define IDS_ADD_BOOKMARK_TIPS           119
#define IDS_OPEN_FILE_FAILED            120
#define IDS_UNKNOWN_FORMAT              121
#define IDS_EMPTY_FILE                  122
#define IDS_INIT_CACHE_FAIL             123
#define IDS_SAVE_CACHE_FAIL             124
#define IDS_EMPTY_KEYWORD               125
#define IDS_EMPTY_REGEX                 126
#define IDS_INVALID_REGEX               127
#define IDS_SAVE_TEXT_TIPS              128
#define IDI_BOOK                        129
#define IDS_SAVE_FILE                   129
#define IDS_SAVE_FAIL                   130
#define IDD_SETTING                     131
#define IDS_KEYVALUE_EMPTY              131
#define IDD_JUMP_PROGRESS               132
#define IDS_KEYVALUE_DUPLICATE          132
#define IDS_REGISTER_FAIL               133
#define IDD_PROXY                       134
#define IDS_REQUEST_CONTENT_FAIL        134
#define IDD_UPGRADE                     135
#define IDS_BOOKSOURCE_EXIST            135
#define IDR_GIF_LOADING                 136
#define IDS_BOOKSOURCE_FULL             136
#define IDD_KEYSET                      137
#define IDS_FIELED_EMPTY                137
#define IDD_ADVSET                      138
#define IDS_NO_BOOKSOURCE               138
#define IDD_REWARD                      139
#define IDS_NETWORK_FAIL                139
#define IDD_TAGSET                      140
#define IDS_DECOMPRESS_FAIL             140
#define IDD_BOOKSOURCE                  141
#define IDS_PARSE_FAIL                  141
#define IDD_ONLINE                      142
#define IDS_SELECT_BOOKSOURCE           142
#define IDS_QUERY                       143
#define IDS_STOP_QUERY                  144
#define IDS_TITLE                       145
#define IDB_PNG_NEW                     145
#define IDS_HIDE_SHOW_WINDOW            146
#define IDD_TAGITEM                     146
#define IDS_HIDE_SHOW_BORDER            147
#define IDD_DISPLAYSET                  147
#define IDS_FULLSRCEEN                  148
#define IDB_BITMAP_PICKER               148
#define IDS_TOPMOST                     149
#define IDC_CURSOR_PICKER               149
#define IDD_ONLINE_STORE_ADD            150
#define IDS_OPEN_FILE                   150
#define IDS_ADD_BOOKMARK                151
#define IDS_AUTO_PAGE                   152
#define IDS_TEXT_SEARCH                 153
#define IDS_PROGRESS_JUMP               154
#define IDS_EDIT_MODE                   155
#define IDS_PAGE_UP                     156
#define IDS_PAGE_DOWN                   157
#define IDS_LINE_UP                     158
#define IDS_LINE_DOWN                   159
#define IDS_CHAPTER_UP                  160
#define IDS_CHAPTER_DOWN                161
#define IDS_FIXED_TIME                  162
#define IDS_DYNAMIC_CALC                163
#define IDS_ENABLE_PROXY                164
#define IDS_DISABLE_PROXY               165
#define IDS_STRETCH                     166
#define IDS_TILE                        167
#define IDS_TILEFLIP                    168
#define IDS_MENU_OPEN                   169
#define IDS_MENU_CLEAR                  170
#define IDS_MENU_EXIT                   171
#define IDS_MENU_FILE                   172
#define IDS_EDIT_MODE_TIPS              173
#define IDS_RESTORE_DEFAULT             174
#define IDS_FONT_ZOOMIN                 175
#define IDS_FONT_ZOOMOUT                176
#define IDS_AUTOPAGING                  177
#define IDS_NOTEXIST_BOOKSOURCE         178
#define IDS_NO_BOOKSOURCE_FAIL          179
#define IDS_BOOK_NAME                   180
#define IDS_AUTHOR                      181
#define IDS_STATUS                      182
#define IDS_MAINPAGE                    183
#define IDS_NULL                        184
#define IDS_QUERYPAGE                   185
#define IDS_ADD_COMPLETED               186
#define IDS_SAVE_COMPLETED              187
#define IDS_IMPORT_COMPLETED            188
#define IDS_IMPORT_FAILED               189
#define IDS_EXPORT_COMPLETED            190
#define IDS_EXPORT_FAILED               191
#define IDS_FILED_MODIFY                192
#define IDS_SINGLE_LINE                 193
#define IDS_DOUBLE_LINE                 194
#define IDS_THREE_LINE                  195
#define IDS_FULL_PAGE                   196
#define IDS_REQUEST_ERROR               197
#define IDS_LOST_WARN                   198
#define IDS_SYNC_FAIL                   199
#define IDS_SYNC_SUCC                   200
#define IDS_AUTO_SYNC                   201
#define IDS_STOP_SYNC                   202
#define IDS_FILE_ISEXIST                203
#define IDS_BOOK_SOURCE                 204
#define IDS_DELETE                      205
#define IDS_MOVE_UP                     206
#define IDS_MOVE_DOWN                   207
#define IDS_DELETE_FILE_CFM             208
#define IDS_CLEAR_ALL_FILES             209
#define IDS_ENABLE                      210
#define IDS_DISABLE                     211
#define IDS_KEYWORD                     212
#define IDS_FONT                        213
#define IDS_BG_COLOR                    214
#define IDS_EDIT                        215
#define IDS_TAGSET_FULL                 216
#define IDS_TAGITEM_EXIST               217
#define IDS_ID                          218
#define IDS_DELETE_CFM                  219
#define IDS_RMALL_CFM                   220
#define IDS_BS_SAVE_TIP                 221
#define IDS_REFRESH_TIP                 222
#define IDS_REGEX                       223
#define IDS_BS_EXIST_TIP                224
#define IDS_CLEAR                       225
#define IDS_CLEAR_BS_CFM                226
#define IDS_DELETE_BS_CFM               227
#define IDS_INVALID_CHARGAP             228
#define IDS_INVALID_PARAGRAPHGAP        229
#define IDS_WEREAD_REFRESH              230
#define IDC_EDIT_LINEGAP                1000
#define IDC_EDIT_BORDER                 1001
#define IDC_EDIT_PARAGRAPHGAP           1002
#define IDC_EDIT_CHARGAP                1003
#define IDC_COMBO_SPEED                 1005
#define IDC_STATIC_LINK                 1016
#define IDC_EDIT_JP                     1017
#define IDC_RADIO_MODE1                 1019
#define IDC_RADIO_MODE2                 1020
#define IDC_RADIO_MODE3                 1021
#define IDC_COMBO_BIMODE                1023
#define IDC_EDIT_BIFILE                 1024
#define IDC_BUTTON_BISEL                1025
#define IDC_CHECK_BIENABLE              1026
#define IDC_EDIT_ELAPSE                 1028
#define IDC_EDIT_PROXY_ADDR             1029
#define IDC_EDIT_PROXY_PORT             1030
#define IDC_EDIT_PROXY_USER             1031
#define IDC_EDIT_PROXY_PASS             1032
#define IDC_COMBO_PROXY                 1033
#define IDC_BUTTON_UPGRADE_INGORE       1034
#define IDC_BUTTON_UPGRADE_DOWN         1035
#define IDC_EDIT_UPGRADE_VERSION        1036
#define IDC_EDIT_UPGRADE_DESC           1037
#define IDC_CHECK_TASKBAR               1038
#define IDC_CHECK_TRAY                  1039
#define IDC_CHECK_LRHIDE                1040
#define IDC_CHECK_ESCHIDE               1041
#define IDC_HK_HIDE                     1042
#define IDC_HK_BORDER                   1043
#define IDC_HK_FULLSCREEN               1045
#define IDC_HK_OPEN                     1046
#define IDC_HK_SEARCH                   1047
#define IDC_HK_TOP                      1048
#define IDC_HK_JUMP                     1049
#define IDC_HK_PAGEUP                   1050
#define IDC_HK_PAGEDOWN                 1051
#define IDC_HK_LINEUP                   1052
#define IDC_HK_LINEDOWN                 1053
#define IDC_HK_CHAPTERUP                1054
#define IDC_HK_CHAPTERDOWN              1055
#define IDC_HK_ADDMARK                  1056
#define IDC_HK_AUTOPAGE                 1057
#define IDC_BUTTON_DEFAULT              1058
#define IDC_RADIO_ATPAGE                1059
#define IDC_HK_FONTZOOMIN               1059
#define IDC_HK_EDIT                     1060
#define IDC_RADIO_ATWHEEL               1061
#define IDC_HK_FONTZOOMOUT              1061
#define IDC_RADIO_CPT_DEFAULT           1063
#define IDC_RADIO_CPT_KEYWORD           1064
#define IDC_RADIO_CPT_REGEX             1065
#define IDC_EDIT_CPT_KEYWORD            1066
#define IDC_EDIT_CPT_REGEX              1067
#define IDC_BUTTON_REWARD               1068
#define IDC_CHECK_MENU_FONT             1110
#define IDC_COMBO_APM                   1111
#define IDC_CHECK_WORD_WRAP             1112
#define IDC_LIST_BOOKSRC                1112
#define IDC_EDIT_HOST                   1113
#define IDC_COMBO_BS_LIST               1114
#define IDC_EDIT_QUERY                  1114
#define IDC_EDIT_QUERY_KEYWORD          1115
#define IDC_EDIT_NAME                   1115
#define IDC_BUTTON_OL_QUERY             1116
#define IDC_EDIT_AUTHOR                 1116
#define IDC_LIST_QUERY                  1117
#define IDC_EDIT_CPT_TITLE              1117
#define IDC_BUTTON_BS_MANAGER           1118
#define IDC_EDIT_CPT_URL                1118
#define IDC_EDIT_CTX_NEXT               1119
#define IDC_EDIT_CTX                    1120
#define IDC_EDIT_MAINPAGE               1121
#define IDC_BUTTON_ADD                  1122
#define IDC_MANUAL                      1122
#define IDC_BUTTON_RMALL                1123
#define IDC_EXPORT                      1126
#define IDC_IMPORT                      1127
#define IDC_COMBO_METHOD                1128
#define IDC_EDIT_LEFTLINE               1129
#define IDC_EDIT_POST                   1129
#define IDC_CHECK_INDENT                1130
#define IDC_COMBO_LISTPAGE              1130
#define IDC_EDIT_LISTPAGE               1131
#define IDC_CHECK_BLANKLINES            1131
#define IDC_COMBO_CHARSET               1132
#define IDC_CHECK_CHAPTER_PAGE          1132
#define IDC_SYNC                        1133
#define IDC_STATIC_PREVIEW              1134
#define IDC_EDIT_CTX_KEYWORD            1134
#define IDC_EDIT_TAGKW                  1135
#define IDC_COMBO_CTX_NEXT              1135
#define IDC_BUTTON_TAGFONT              1136
#define IDC_EDIT_CTX_KEYWORD_TXT        1136
#define IDC_BUTTON_TAGBG                1137
#define IDC_COMBO_CPT_NEXT              1137
#define IDC_LIST_TAGSET                 1138
#define IDC_EDIT_CPT_NEXT               1138
#define IDC_EDIT_TITLE                  1139
#define IDC_CHECK                       1140
#define IDC_COMBO_FILTER                1140
#define IDC_CHECK_HIDE                  1141
#define IDC_EDIT_CPT_KEYWORD_TXT        1141
#define IDC_CHECK_BORDER                1142
#define IDC_EDIT_FILTER                 1142
#define IDC_CHECK_FULLSCREEN            1143
#define IDC_CHECK_TOP                   1144
#define IDC_CHECK_OPEN                  1145
#define IDC_CHECK_ADDMARK               1146
#define IDC_CHECK_AUTOPAGE              1147
#define IDC_CHECK_SEARCH                1148
#define IDC_CHECK_JUMP                  1149
#define IDC_CHECK_EDIT                  1150
#define IDC_CHECK_PAGEUP                1151
#define IDC_CHECK_PAGEDOWN              1152
#define IDC_CHECK_LINEUP                1153
#define IDC_CHECK_LINEDOWN              1154
#define IDC_CHECK_CHAPTERUP             1155
#define IDC_CHECK_CHAPTERDOWN           1156
#define IDC_CHECK_FONTZOOMIN            1157
#define IDC_CHECK_FONTZOOMOUT           1158
#define IDC_STATIC_VERSION              1159
#define IDC_BUTTON_FOLLOW               1161
#define IDC_BUTTON_TEXT_FONT            1162
#define IDC_CHECK_SAME                  1163
#define IDC_BUTTON_CHAPTER_FONT         1164
#define IDC_BUTTON_BGCOLOR              1165
#define IDC_STATIC_PICKER               1168
#define IDC_STATIC_RGB                  1169
#define IDC_HK_WEREAD_REFRESH           1170
#define IDC_CHECK_WEREAD_REFRESH        1171
#define IDC_EDIT_ALPHA                  1172
#define IDC_CHECK_TEXT_OPAQUE_BG_TRANSPARENT 1173
#define IDC_CHECK_MOUSE_LEAVE_HIDE      1174
#define IDC_EDIT_ONLINE_STORE_URL       1175
#define IDC_EDIT_ONLINE_STORE_NAME      1176
#define IDC_CHECK_WEBVIEW_TRANSPARENT_BG 1177
#define IDC_STATIC_TEXT_FONT_PICKER     1178
#define IDC_STATIC_CHAPTER_FONT_PICKER  1179
#define IDM_OPEN                        32771
#define IDM_DISPLAY                     32772
#define IDM_DEFAULT                     32781
#define IDM_VIEW                        32784
#define IDM_CLEAR                       32788
#define IDM_CONFIG                      32790
#define IDM_PROXY                       32794
#define IDM_MARK                        32798
#define IDM_KEYSET                      32801
#define IDM_ADVSET                      32802
#define IDM_TAGSET                      32803
#define IDM_ONLINE                      32804
#define IDM_WEREAD                      32805
#define IDM_ONLINE_STORE_ADD            32806
#define IDM_ONLINE_STORE_FIRST          32900
#define IDM_ONLINE_STORE_DELETE_FIRST   33000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1180
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
